[features]
seeds = false
skip-lint = false
[programs.localnet]
puppet = "BdTgodfbn4PBz5zgj2EoGU6b7owYWXY17y6ZK4DM12qR"
puppet-master = "FwsAUMA78s66U2LSrEmRWeSP4zdqc3yuz1gH1zndZ6cq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/almei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
